/* Volumetric stream bundles, perspective projection and a continuous camera spline. */
(()=>{'use strict';
const canvas=document.getElementById('world'),ctx=canvas.getContext('2d'),journey=document.getElementById('journey'),stage=journey.querySelector('.stage'),titles=[...document.querySelectorAll('.chapter')],left=document.querySelector('.label-left'),right=document.querySelector('.label-right'),motion=document.querySelector('.motion'),media=matchMedia('(prefers-reduced-motion: reduce)');
let reduced=media.matches,paused=false,w=0,h=0,mobile=false,range=1,progress=0,target=0,time=0,last=0,raf=0,entrance=0,ready=false;
const pointer={x:0,y:0},cursor={x:0,y:0},clamp=(x,a=0,b=1)=>Math.max(a,Math.min(b,x)),mix=(a,b,t)=>a+(b-a)*t,smooth=t=>{t=clamp(t);return t*t*(3-2*t);};
let seed=81;const rand=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};
const lanes=Array.from({length:72},(_,i)=>{const angle=i*2.399963, radius=.3+Math.sqrt(rand())*.7;return{angle,radius,phase:rand()*Math.PI*2,offset:rand(),speed:.7+rand()*.4,size:rand()};});
const V=(x,y,z)=>({x,y,z}),sub=(a,b)=>V(a.x-b.x,a.y-b.y,a.z-b.z),dot=(a,b)=>a.x*b.x+a.y*b.y+a.z*b.z,cross=(a,b)=>V(a.y*b.z-a.z*b.y,a.z*b.x-a.x*b.z,a.x*b.y-a.y*b.x),norm=a=>{const l=Math.hypot(a.x,a.y,a.z)||1;return V(a.x/l,a.y/l,a.z/l);};
// Cubic interpolation keeps camera velocity continuous through the middle composition.
const cameraKeys=[{pos:V(0,90,1900),look:V(0,0,0)},{pos:V(170,480,1630),look:V(0,0,-60)},{pos:V(0,510,1420),look:V(0,-170,-3100)}];
function spline(a,b,c,d,t){const t2=t*t,t3=t2*t;return .5*((2*b)+(-a+c)*t+(2*a-5*b+4*c-d)*t2+(-a+3*b-3*c+d)*t3);}
function camera(p){const i=Math.min(1,Math.floor(p)),t=p-i,at=k=>cameraKeys[clamp(k,0,2)];const sample=key=>V(...['x','y','z'].map(axis=>spline(at(i-1)[key][axis],at(i)[key][axis],at(i+1)[key][axis],at(i+2)[key][axis],t)));const pos=sample('pos'),look=sample('look');pos.x+=cursor.x*85;pos.y+=cursor.y*48;look.x+=cursor.x*12;look.y+=cursor.y*8;const f=norm(sub(look,pos)),r=norm(cross(f,V(0,1,0))),up=cross(r,f);return{pos,f,r,up,merge:smooth(p-1),focal:1420};}
function point(lane,u,side,c){const s=1-u,envelope=Math.pow(s,.85),flow=time*.16,angle=lane.angle+Math.sin(u*3+flow)*.22+u*1.35;const radial=lane.radius;
// Cross-sections are elliptical volumes: strands pass in front of and behind one another.
const initial=V(side*(1420*s+Math.sin(u*Math.PI)*100),Math.sin(angle)*radial*490*envelope+Math.sin(u*5+flow+lane.phase)*42*envelope,Math.cos(angle)*radial*800*envelope+Math.sin(u*4+lane.phase+flow)*65*envelope);
const twist=lane.angle+u*.35+Math.sin(flow+u*2)*.09;
const final=V(Math.sin(twist)*radial*1050+Math.sin(u*4+flow)*45,-330+Math.cos(twist)*radial*210+Math.sin(u*5+flow)*28,1050-u*7000);
return V(mix(initial.x,final.x,c.merge),mix(initial.y,final.y,c.merge),mix(initial.z,final.z,c.merge));}
function project(v,c){const q=sub(v,c.pos),z=dot(q,c.f);if(z<90)return null;const scale=c.focal/z;return{x:w*.5+dot(q,c.r)*scale*w/1920,y:h*mix(.5,.395,c.merge)-dot(q,c.up)*scale*h/1080,scale,z};}
function draw(){if(!ctx)return;ctx.clearRect(0,0,w,h);const c=camera(reduced?target:progress),segments=[],dots=[],stride=mobile?2:1;
// Soft, broad illumination gives the bundles volume without bloom or neon halos.
const light=ctx.createRadialGradient(w*.52,h*.52,0,w*.52,h*.52,w*.52);light.addColorStop(0,'rgba(18,63,67,.10)');light.addColorStop(1,'rgba(0,18,34,0)');ctx.fillStyle=light;ctx.fillRect(0,0,w,h);
for(let n=0;n<lanes.length;n+=stride){const lane=lanes[n],lit=.5+.5*Math.sin(lane.angle+.8);for(const side of [-1,1]){if(side===-1||c.merge<.999){let prev=null;const steps=mobile?44:60;for(let j=0;j<=steps;j++){const q=project(point(lane,j/steps,side,c),c);if(q&&prev){const depth=(q.z+prev.z)*.5,alpha=clamp(1800/depth,.15,1)*(.08+lit*.16)*(side>0?1-c.merge:1);segments.push({a:prev,b:q,z:depth,alpha,green:side>0,lit});}prev=q;}}
for(let j=0;j<8;j++){const u=(j/8+lane.offset+(side>0?.0625:0)+time*.026*lane.speed)%1,q=project(point(lane,u,side,c),c);if(!q||q.x< -12||q.x>w+12||q.y< -12||q.y>h+12)continue;const tone=(j+n)%5,colour=side<0?(tone<2?'#FFFFFF':'#8B9BA6'):(tone<3?'#00D16A':'#062D2C');const size=clamp((lane.size>.72?5.5:3)*q.scale*Math.max(.38,w/1920),.65,9);dots.push({...q,size,colour,green:side>0,lit,alpha:clamp((1-u)*30)*clamp(u*35)*clamp(2600/q.z,.2,1)});}}}
segments.sort((a,b)=>b.z-a.z);for(const seg of segments){ctx.strokeStyle=seg.green?`rgba(0,158,99,${seg.alpha})`:`rgba(143,180,186,${seg.alpha})`;ctx.lineWidth=clamp(1100/seg.z,.3,1.05);ctx.beginPath();ctx.moveTo(seg.a.x,seg.a.y);ctx.lineTo(seg.b.x,seg.b.y);ctx.stroke();}
dots.sort((a,b)=>b.z-a.z);for(const d of dots){const x=d.x-d.size/2,y=d.y-d.size/2,face=d.size*.23;ctx.globalAlpha=d.alpha;
if(d.size>2.5){ctx.fillStyle='rgba(0,8,16,.32)';ctx.fillRect(x+face,y+face,d.size,d.size);}
ctx.fillStyle=d.colour;ctx.fillRect(x,y,d.size,d.size);
if(d.size>3){ctx.fillStyle=d.green?'rgba(0,42,30,.42)':'rgba(0,18,34,.32)';ctx.fillRect(x+d.size-face,y,face,d.size);ctx.fillStyle=`rgba(255,255,255,${.07+d.lit*.1})`;ctx.fillRect(x,y,d.size-face,Math.max(.5,face*.5));}}
ctx.globalAlpha=1;}
function updateUI(){const p=progress,merge=smooth(p-1),intro=reduced?1:smooth(entrance),a=1-smooth((p-.12)/.36),b=smooth((p-.5)/.35)*(1-smooth((p-1.12)/.55));titles.forEach((el,i)=>{const alpha=(i?b:a)*intro,dy=reduced?0:(i?(1-smooth((p-.5)/.35))*22-smooth((p-1.12)/.55)*22:(1-intro)*24-smooth((p-.12)/.36)*22);el.style.opacity=alpha;el.style.transform=`translate(-50%,calc(-50% + ${dy}px))`;el.setAttribute('aria-hidden',alpha<.1);});
const y=mix(mobile?.66:569/1080,359/1080,merge)*100;left.style.top=right.style.top=y+'%';if(mobile){left.style.left=`calc(${mix(6,50,merge)}% - ${merge*87}px)`;right.style.right=`calc(${mix(6,50,merge)}% - ${merge*81}px)`;}else{left.style.left=mix(251/1920,808/1920,merge)*100+'%';right.style.right=mix(249/1920,913/1920,merge)*100+'%';}stage.dataset.scene=p<.5?'start':p<1.5?'one-scroll':'two-scroll';}
function frame(now){raf=0;if(document.hidden||!ready)return;const dt=last?Math.min((now-last)/1000,.05):1/60;last=now;progress=reduced?target:mix(progress,target,1-Math.exp(-4.3*dt));if(Math.abs(progress-target)<.0001)progress=target;const ck=1-Math.exp(-3.4*dt);cursor.x=mix(cursor.x,pointer.x,ck);cursor.y=mix(cursor.y,pointer.y,ck);if(!paused&&!reduced)time+=dt;entrance=Math.min(1,entrance+dt/1.1);updateUI();draw();const visible=scrollY<journey.offsetTop+journey.offsetHeight&&scrollY+innerHeight>journey.offsetTop;if((visible&&!paused&&!reduced)||Math.abs(progress-target)>.0001||Math.abs(cursor.x-pointer.x)>.001||Math.abs(cursor.y-pointer.y)>.001||entrance<1)wake();}
function wake(){if(!raf&&!document.hidden&&ready)raf=requestAnimationFrame(frame);}
function scroll(){target=clamp((scrollY-journey.offsetTop)/range)*2;wake();}
function resize(){w=stage.clientWidth;h=stage.clientHeight;mobile=w<=700;const dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);if(ctx)ctx.setTransform(dpr,0,0,dpr,0,0);range=Math.max(1,journey.offsetHeight-h);scroll();wake();}
window.addEventListener('resize',resize);window.addEventListener('scroll',scroll,{passive:true});stage.addEventListener('pointermove',e=>{if(e.pointerType==='touch'||reduced)return;pointer.x=(e.clientX/w-.5)*2;pointer.y=(.5-e.clientY/h)*2;wake();},{passive:true});stage.addEventListener('pointerleave',()=>{pointer.x=pointer.y=0;wake();});document.addEventListener('visibilitychange',()=>{last=0;if(document.hidden){cancelAnimationFrame(raf);raf=0;}else wake();});media.addEventListener('change',e=>{reduced=e.matches;pointer.x=pointer.y=0;wake();});motion.addEventListener('click',()=>{paused=!paused;motion.setAttribute('aria-pressed',paused);motion.textContent=paused?'Play animation':'Pause animation';wake();});document.fonts.ready.then(()=>{ready=true;resize();});
})();
