/* Joining Forces: a continuous 3D path system, projected into a lightweight canvas. */
(()=>{'use strict';
const CONFIG={desktopPaths:100,mobilePaths:54,particlesPerPath:11,particleSpeed:.027,scrollSmoothing:5.5,cursorSmoothing:3.4,cursorInfluence:65,maxDpr:1.6,green:[0,214,111],white:[220,233,233],grey:[111,143,155]};
const canvas=document.getElementById('world'),ctx=canvas.getContext('2d'),journey=document.getElementById('journey'),stage=journey.querySelector('.stage'),chapters=[...document.querySelectorAll('.chapter')],buttons=[...document.querySelectorAll('[data-go]')],ticks=buttons.map(b=>b.querySelector('.tick')),count=document.getElementById('count'),hint=document.getElementById('scroll-hint');
const media=matchMedia('(prefers-reduced-motion: reduce)');let reduced=media.matches,paused=false,w=0,h=0,mobile=false,paths=[],progress=0,target=0,clock=0,last=0,raf=0,active=-1,pointer={x:0,y:0},cursor={x:0,y:0},dirty=true,range=1;
const clamp=(x,a=0,b=1)=>Math.max(a,Math.min(b,x)),mix=(a,b,t)=>a+(b-a)*t,ease=t=>{t=clamp(t);return t*t*(3-2*t);};
let seed=81;function rand(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;}
const V=(x,y,z)=>({x,y,z}),sub=(a,b)=>V(a.x-b.x,a.y-b.y,a.z-b.z),dot=(a,b)=>a.x*b.x+a.y*b.y+a.z*b.z,cross=(a,b)=>V(a.y*b.z-a.z*b.y,a.z*b.x-a.x*b.z,a.x*b.y-a.y*b.x),norm=a=>{const l=Math.hypot(a.x,a.y,a.z)||1;return V(a.x/l,a.y/l,a.z/l);},lerp=(a,b,t)=>V(mix(a.x,b.x,t),mix(a.y,b.y,t),mix(a.z,b.z,t));
const keys=[{pos:V(0,160,1250),look:V(0,0,-80)},{pos:V(80,60,-470),look:V(0,0,-1800)},{pos:V(420,240,-1550),look:V(-80,-70,-3200)},{pos:V(2200,1100,120),look:V(0,0,-1800)}];
function camera(p){const i=Math.min(2,Math.floor(p)),t=ease(p-i);let pos=lerp(keys[i].pos,keys[i+1].pos,t),look=lerp(keys[i].look,keys[i+1].look,t);const influence=reduced?0:CONFIG.cursorInfluence;pos.x+=cursor.x*influence;pos.y+=cursor.y*influence*.55;const forward=norm(sub(look,pos)),right=norm(cross(forward,V(0,1,0))),up=cross(right,forward);return{pos,forward,right,up,focal:Math.min(w,h)*(mobile?1.08:1.18)};}
function project(v,c){const q=sub(v,c.pos),z=dot(q,c.forward);if(z<45)return null;const scale=c.focal/z;return{x:w*.5+dot(q,c.right)*scale,y:h*.635-dot(q,c.up)*scale,z,scale};}
function point(path,u,time){let x,y,z;const breathing=Math.sin(time*.35+path.phase)*5;if(u<.32){const t=u/.32,s=1-t;const spread=Math.pow(s,1.25);x=path.side*(s*(mobile?700:1500)+Math.sin(t*Math.PI)*70);y=path.y*spread+Math.sin(t*Math.PI*1.2+path.phase)*55*s+path.lane*6+breathing*s;z=path.z*spread-80*t+Math.sin(t*Math.PI)*path.depth;}else{const t=(u-.32)/.68,spread=ease(t*2.8);x=path.branch*290*spread+Math.sin(t*6+path.phase*.15)*70*spread+path.lane*10;y=path.y*.35*spread+Math.cos(t*6+path.phase*.2)*70*spread+path.lane*5+breathing;z=-80-t*4300;}return V(x,y,z);}
function build(){seed=81;paths=[];const n=mobile?CONFIG.mobilePaths:CONFIG.desktopPaths;for(let i=0;i<n;i++)paths.push({side:i%2?1:-1,y:(rand()-.5)*1350,z:(rand()-.5)*900,depth:(rand()-.5)*650,lane:(rand()-.5)*6,phase:rand()*Math.PI*2,branch:i%3-1,green:rand()<.3,speed:.75+rand()*.55,offset:rand(),size:.7+rand()*1.6});}
function resize(){w=stage.clientWidth;h=stage.clientHeight;const was=mobile;mobile=w<701;const dpr=Math.min(devicePixelRatio||1,CONFIG.maxDpr);canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);if(ctx)ctx.setTransform(dpr,0,0,dpr,0,0);range=Math.max(1,journey.offsetHeight-h);if(!paths.length||was!==mobile)build();scroll();dirty=true;wake();}
function scroll(){target=clamp((scrollY-journey.offsetTop)/range)*3;dirty=true;wake();}
function updateUI(p){const index=Math.min(3,Math.round(p));if(index!==active){active=index;chapters.forEach((el,i)=>{el.setAttribute('aria-hidden',i!==index);el.inert=i!==index;el.classList.toggle('active',i===index);});buttons.forEach((b,i)=>{if(i===index)b.setAttribute('aria-current','step');else b.removeAttribute('aria-current');b.classList.toggle('green',i>=2);});count.textContent='0'+(index+1)+' / 04';hint.innerHTML=index===0?'SCROLL THROUGH WHAT WE CAN DO TOGETHER <b>↓</b>':index===3?'YOUR NEXT CHAPTER <b>↓</b>':'KEEP EXPLORING <b>↓</b>';}
chapters.forEach((el,i)=>{const distance=Math.abs(p-i),alpha=1-ease((distance-.18)/.43);el.style.opacity=alpha;el.style.transform=`translateY(${reduced?0:(i-p)*25}px)`;});ticks.forEach((el,i)=>{const influence=Math.exp(-Math.pow((p-i)*2.1,2));el.style.height=((mobile?23:32)+influence*(mobile?46:64))+'px';});const fade=1-ease(p*1.5);document.querySelectorAll('.field-label').forEach(el=>el.style.opacity=fade);document.querySelector('.system-labels').style.opacity=ease(p-1.25)*(1-ease(p-2.65));}
function draw(p,time){if(!ctx)return;ctx.clearRect(0,0,w,h);const c=camera(reduced?0:p);const mot=reduced?0:time;
// Quiet spatial reference particles, kept sparse and deterministic.
ctx.fillStyle='rgba(150,177,186,.16)';for(let i=0;i<65;i++){const v=V(Math.sin(i*73.13)*1800,Math.cos(i*19.7)*1100,-(i*137)%4300);const q=project(v,c);if(q&&q.x>0&&q.x<w&&q.y>0&&q.y<h)ctx.fillRect(q.x,q.y,1,1);}
for(const path of paths){ctx.beginPath();let pen=false;const steps=mobile?63:87;for(let j=0;j<=steps;j++){const q=project(point(path,j/steps,mot),c);if(!q||q.x< -w*2||q.x>w*3||q.y< -h*2||q.y>h*3){pen=false;continue;}if(!pen){ctx.moveTo(q.x,q.y);pen=true;}else ctx.lineTo(q.x,q.y);}const colour=path.green?CONFIG.green:CONFIG.grey;ctx.strokeStyle=`rgba(${colour},${path.green?.19:.18})`;ctx.lineWidth=path.green?.65:.5;ctx.stroke();}
const dots=[];for(const path of paths){for(let j=0;j<CONFIG.particlesPerPath;j++){const u=(j/CONFIG.particlesPerPath+path.offset+mot*CONFIG.particleSpeed*path.speed)%1;const q=project(point(path,u,mot),c);if(!q||q.x< -20||q.x>w+20||q.y< -20||q.y>h+20)continue;const s=clamp(path.size*q.scale*2.5,.8,5.2);const edge=Math.min(clamp(u*40),clamp((1-u)*30));const a=clamp(.18+q.scale*.72,.18,.94)*edge;dots.push({...q,size:s,alpha:a,green:path.green,white:j%4===0});}}dots.sort((a,b)=>b.z-a.z);for(const d of dots){const col=d.green?CONFIG.green:d.white?CONFIG.white:CONFIG.grey;ctx.fillStyle=`rgba(${col},${d.alpha})`;ctx.fillRect(d.x-d.size/2,d.y-d.size/2,d.size,d.size);if(d.green&&d.size>3.5){ctx.fillStyle=`rgba(${CONFIG.green},.04)`;ctx.fillRect(d.x-d.size*1.6,d.y-d.size*1.6,d.size*3.2,d.size*3.2);}}
}
function frame(now){raf=0;if(document.hidden)return;const dt=last?Math.min((now-last)/1000,.05):1/60;last=now;const k=1-Math.exp(-CONFIG.scrollSmoothing*dt);progress=reduced?target:mix(progress,target,k);if(Math.abs(progress-target)<.0002)progress=target;const ck=1-Math.exp(-CONFIG.cursorSmoothing*dt);cursor.x=mix(cursor.x,pointer.x,ck);cursor.y=mix(cursor.y,pointer.y,ck);if(!paused&&!reduced)clock+=dt;updateUI(progress);draw(progress,clock);dirty=false;const visible=scrollY<journey.offsetHeight&&scrollY+innerHeight>journey.offsetTop;if((visible&&!paused&&!reduced)||Math.abs(progress-target)>.0002||Math.abs(cursor.x-pointer.x)>.001||Math.abs(cursor.y-pointer.y)>.001)raf=requestAnimationFrame(frame);}
function wake(){if(!raf&&!document.hidden)raf=requestAnimationFrame(frame);}
function go(i){window.scrollTo({top:journey.offsetTop+range*i/3,behavior:reduced?'instant':'smooth'});}
buttons.forEach(b=>b.addEventListener('click',()=>go(Number(b.dataset.go))));document.getElementById('replay').addEventListener('click',()=>go(0));
const motion=document.querySelector('.motion');function motionLabel(){motion.setAttribute('aria-pressed',paused||reduced);motion.querySelector('.motion-text').textContent=reduced?'Reduced motion':paused?'Play motion':'Pause motion';motion.querySelector('.pause-icon').textContent=paused||reduced?'▷':'Ⅱ';motion.title=reduced?'Reduced motion follows your device preference':paused?'Play ambient motion':'Pause ambient motion';}
motion.addEventListener('click',()=>{if(reduced)return;paused=!paused;motionLabel();dirty=true;wake();});
media.addEventListener('change',e=>{reduced=e.matches;document.body.classList.toggle('reduced',reduced);motionLabel();resize();});document.body.classList.toggle('reduced',reduced);motionLabel();
window.addEventListener('scroll',scroll,{passive:true});window.addEventListener('resize',resize);stage.addEventListener('pointermove',e=>{if(e.pointerType==='touch'||reduced)return;pointer.x=(e.clientX/w-.5)*2;pointer.y=(.5-e.clientY/h)*2;wake();},{passive:true});stage.addEventListener('pointerleave',()=>{pointer.x=pointer.y=0;wake();});document.addEventListener('visibilitychange',()=>{last=0;if(document.hidden){cancelAnimationFrame(raf);raf=0;}else wake();});
const questions={performance:'Where could your payments perform better?',operations:'What could your team achieve with less complexity?',expansion:'What does your next market need from your platform?'};
document.querySelectorAll('[data-priority]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-priority]').forEach(other=>{const selected=other===b;other.classList.toggle('selected',selected);other.setAttribute('aria-pressed',selected);});document.getElementById('priority-question').textContent=questions[b.dataset.priority];document.getElementById('evaluation-link').href='../index.html?priority='+b.dataset.priority+'#evaluate';}));
if(!ctx)document.body.classList.add('no-canvas');resize();
})();
